### ISSUE TITLE
New Tenant added in one node not getting identified by other nodes without node restart

### ISSUE THREAD

**Issue by Purbaja** [ConsenSys/quorum#1318] opened 2022-02-01 05:05 UTC
Opening this issue as solution not yet working as provided in (https://github.com/ConsenSys/quorum/issues/1278) 

Hi @macfarla , As suggested I checked with the partyinfo command in both the nodes and here is the output-

Response from Node1 :
curl -X GET http://x.x.x.x:9080/partyinfo/keys
{"keys":[{"key":"G27/Rz02qexxYTI7h54W9Ebzoz3LgFppBhLSWbzgxCA="},{"key":"swAqIm6pDee0Y2mTEH7wmFPFPoK7QQL3WdZzXBVeASQ="}]}
***** this keys are of default tenant and Tenant1 of Node1

Response from Node2:
curl -X GET http://y.y.y.y:9080/partyinfo/keys
{"keys":[{"key":"O/ruD6wozXhv8FNg5WTlDDUY4LA9p/StZLzTFeGajW8="}]}
*** this keys are of default tenant of Node2

_Originally posted by @Purbaja in https://github.com/ConsenSys/quorum/issues/1278#issuecomment-1023343518_

**Comment by MadelineMurray** [comment] 2022-02-14 03:51
Duplicate of #1278 so have reopened that one.

**Closed as completed by MadelineMurray** 2022-02-14 03:51 UTC
